version: '3.8'
services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ../tmp/redis:/data
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: sleep infinity
    volumes:
      - ../..:/ws:cached